# Generated by Django 4.2.24 on 2025-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
