# Generated by Django 4.2.24 on 2025-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_api_key_profile_api_key_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
