# Generated by Django 4.2.24 on 2025-10-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], help_text='AI-detected sentiment based on message and rating.', max_length=20, null=True)),
                ('sentiment_score', models.FloatField(blank=True, help_text='A numeric score between 0 (negative) and 1 (positive).', null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('suggestions', models.JSONField(blank=True, default=list, null=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='User-provided rating from 1 to 5.')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='form.form')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
